//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sueetie {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sueetie() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Sueetie", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Album Paths.
        /// </summary>
        internal static string Admin_Add_Media_AlbumPaths_Hdr {
            get {
                return ResourceManager.GetString("Admin_Add_Media_AlbumPaths_Hdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Media Content.
        /// </summary>
        internal static string Admin_Add_Media_General_Hdr {
            get {
                return ResourceManager.GetString("Admin_Add_Media_General_Hdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Album Paths.
        /// </summary>
        internal static string Admin_Media_Sueetie_AlbumPaths_Link_Text {
            get {
                return ResourceManager.GetString("Admin_Media_Sueetie_AlbumPaths_Link_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Media Content.
        /// </summary>
        internal static string Admin_Media_Sueetie_Content_Link_Text {
            get {
                return ResourceManager.GetString("Admin_Media_Sueetie_Content_Link_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sueetie.
        /// </summary>
        internal static string Admin_Sueetie_Hdr_Text {
            get {
                return ResourceManager.GetString("Admin_Sueetie_Hdr_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string Admin_Task_SueetieContent_Ok_Button_Text {
            get {
                return ResourceManager.GetString("Admin_Task_SueetieContent_Ok_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check items you want to be displayed in the Sueetie Download Report. Only selected media objects will be included. Album selections are ignored..
        /// </summary>
        internal static string Include_Download_Objects_Body_Text {
            get {
                return ResourceManager.GetString("Include_Download_Objects_Body_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include items in Sueetie Download Report.
        /// </summary>
        internal static string Include_Download_Objects_Header_Text {
            get {
                return ResourceManager.GetString("Include_Download_Objects_Header_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Selected Items.
        /// </summary>
        internal static string Include_Download_Objects_Ok_Button_Text {
            get {
                return ResourceManager.GetString("Include_Download_Objects_Ok_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The items you select will be displayed in the Sueetie Download Report. Only selected media objects will be included. Album selections are ignored..
        /// </summary>
        internal static string Include_Download_Objects_Ok_Button_Tooltip1 {
            get {
                return ResourceManager.GetString("Include_Download_Objects_Ok_Button_Tooltip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include items in the Sueetie Download Report.
        /// </summary>
        internal static string Include_Download_Objects_Page_Title {
            get {
                return ResourceManager.GetString("Include_Download_Objects_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To avoid an error on the initial load of our rocking Media Gallery, a simple flag was added to the /media app.config file.  SUEETIE.InstallGSP = 1, which triggers Gallery Server Pro&apos;s installation wizard. Remember to change the app.config SUEETIE.InstallGSP property to &quot;0&quot; when you complete this wizard.  If you are seeing this installation wizard for the second time, this is why..
        /// </summary>
        internal static string Installer_AppConfig_Description {
            get {
                return ResourceManager.GetString("Installer_AppConfig_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop what you&apos;re doing to update the /[mediafolder]/app.config file by changing the SUEETIE.InstallGSP property to &quot;0&quot; to signify that you installed the Media Gallery.  Also touch the web.config while you&apos;re at it to make sure the new app.config SUEETIE.InstallGSP property takes affect.  Then click on the &quot;Go to Media Gallery&quot; link and enjoy your most excellent Media Gallery..
        /// </summary>
        internal static string Installer_AppConfig_Description_End {
            get {
                return ResourceManager.GetString("Installer_AppConfig_Description_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention Sueetie Listeners!.
        /// </summary>
        internal static string Installer_AppConfig_Title {
            get {
                return ResourceManager.GetString("Installer_AppConfig_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery Server Pro has been successfully configured. &lt;a href=&apos;{0}&apos;&gt;Return to the Sueetie Setup Page&lt;/a&gt;.
        /// </summary>
        internal static string Installer_Return {
            get {
                return ResourceManager.GetString("Installer_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Photos.
        /// </summary>
        internal static string Menulink_RecentPhotos {
            get {
                return ResourceManager.GetString("Menulink_RecentPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention: This album does not contain any albums or media objects. Therefore, there is nothing to include in the Sueetie Downloads Report..
        /// </summary>
        internal static string Msg_CannotIncludeObjectsNoObjectsExistInAlbum_Dtl {
            get {
                return ResourceManager.GetString("Msg_CannotIncludeObjectsNoObjectsExistInAlbum_Dtl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include media objects in Sueetie Download Report aborted....
        /// </summary>
        internal static string Msg_CannotIncludeObjectsNoObjectsExistInAlbum_Hdr {
            get {
                return ResourceManager.GetString("Msg_CannotIncludeObjectsNoObjectsExistInAlbum_Hdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media objects were included or removed from the Sueetie Download Report based on your selections..
        /// </summary>
        internal static string Msg_ObjectsSuccessfullyIncluded_Dtl {
            get {
                return ResourceManager.GetString("Msg_ObjectsSuccessfullyIncluded_Dtl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects successfully processed....
        /// </summary>
        internal static string Msg_ObjectsSuccessfullyIncluded_Hdr {
            get {
                return ResourceManager.GetString("Msg_ObjectsSuccessfullyIncluded_Hdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Sueetie Album Details.
        /// </summary>
        internal static string UC_ActionMenu_EditSueetieAlbums_Text {
            get {
                return ResourceManager.GetString("UC_ActionMenu_EditSueetieAlbums_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit album details for Sueetie List View.
        /// </summary>
        internal static string UC_ActionMenu_EditSueetieAlbums_Tip {
            get {
                return ResourceManager.GetString("UC_ActionMenu_EditSueetieAlbums_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Sueetie Media Object Details.
        /// </summary>
        internal static string UC_ActionMenu_EditSueetieCaptions_Text {
            get {
                return ResourceManager.GetString("UC_ActionMenu_EditSueetieCaptions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit media object properties for Sueetie List View.
        /// </summary>
        internal static string UC_ActionMenu_EditSueetieCaptions_Tip {
            get {
                return ResourceManager.GetString("UC_ActionMenu_EditSueetieCaptions_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include in Download Report.
        /// </summary>
        internal static string UC_ActionMenu_Include_Download_Text {
            get {
                return ResourceManager.GetString("UC_ActionMenu_Include_Download_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag items in this album to be displayed in the Sueetie Download Report.
        /// </summary>
        internal static string UC_ActionMenu_Include_Download_Tip {
            get {
                return ResourceManager.GetString("UC_ActionMenu_Include_Download_Tip", resourceCulture);
            }
        }
    }
}
